name: technique
version:  0.2.5
synopsis: Procedures and Sequences
description: |
  A domain specific lanaguage for procedures.

stability: experimental
license: MIT
license-file: LICENSE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2002-2020 Operational Dynamics and Others
category: Tools
tested-with: GHC == 8.8
github: oprdyn/technique

dependencies:
  - base >= 4.11 && < 5
  - ivar-simple
  - containers
  - core-data >= 0.2.1
  - core-text >= 0.2.3.1
  - core-program >= 0.2.4.2
  - dlist
  - free
  - megaparsec
  - text
  - parser-combinators
  - prettyprinter
  - prettyprinter-ansi-terminal
  - hspec

ghc-options: -Wall -Wwarn -fwarn-tabs

library:
  dependencies:
    - async
    - hashable
    - mtl
    - transformers
    - uuid-types
  source-dirs: lib
  exposed-modules:
    - Technique.Builtins
    - Technique.Diagnostics
    - Technique.Evaluator
    - Technique.Failure
    - Technique.Formatter
    - Technique.Language
    - Technique.Internal
    - Technique.Parser
    - Technique.Quantity
    - Technique.Translate
  other-modules: []

executables:
  technique:
    dependencies:
      - technique
    ghc-options: -threaded
    source-dirs: src
    main: TechniqueMain.hs
    other-modules:
      - TechniqueUser

tests:
  check:
    dependencies:
      - hspec
      - technique
    ghc-options: -threaded
    source-dirs:
      - tests
    main: TestSuite.hs
    other-modules:
      - CheckConcreteSyntax
      - CheckSkeletonParser
      - CheckQuantityBehaviour
      - CheckTranslationPhase
      - CheckEvaluationPhase
      - ExampleProcedure
